spring:
  jpa:
    open-in-view: true
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      email: adminus@adminius.io
      first-name: Adminus
      last-name: Administratius
    filter:
      create: true
server:
  port: 8082
