camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: true
    history-level: activity
    id-generator: simple
    admin-user:
      id: admin
      password: admin
